### ISSUE TITLE
Temperature utility deprecated since HA 2022.10, will stop working in 2023.4

### ISSUE THREAD

**Issue by tstabrawa** [Limych/ha-snowtire#116]
**Environment**

- Home Assistant Core release with the issue: 2023.2.3, presumably also all versions >= 2022.10, based on the error message text
- This custom component release with the issue: Snowtire sensor 1.4.5
- Last working this custom component release (if known): Unknown
- Operating environment (Home Assistant/Supervisor/Docker/venv): HA supervised

**Describe the bug**

The following warning is logged by Home Assistant upon startup:

```text
2023-02-12 23:50:03.979 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for snowtire using this method at custom_components/snowtire/binary_sensor.py, line 147: temperature = convert_temperature(
```

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

Restart Home Assistant.  Observe warning in HA logs.

**Expected behavior**

Ideally, no warnings would be logged.

**Debug log**

```text
2023-02-12 23:50:03.979 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for snowtire using this method at custom_components/snowtire/binary_sensor.py, line 147: temperature = convert_temperature(
```

**Additional context**

N/A

**Comment by tjorim** [comment]
@Limych It stopped working for me in 2023.11.0b0:
```
Logger: homeassistant.config
Source: config.py:923
First occurred: 21:33:54 (1 occurrences)
Last logged: 21:33:54

Platform error: binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 923, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/snowtire/binary_sensor.py", line 39, in <module>
    from homeassistant.util.temperature import convert as convert_temperature
ModuleNotFoundError: No module named 'homeassistant.util.temperature'
```

**Comment by LukaszP2** [comment]
Same to me

**Comment by fcastilloec** [comment]
Now that 2023.11.0 has been released, this bug will hit everybody.
I see there's a PR #119 that seems to fix this issue, any chance it could be reviewed and merged?

For anybody else that's affected by this issue, I just replaced the two lines of code inside `custom_components/snowtire/binary_sensor.py` [as shown in the PR](https://github.com/Limych/ha-snowtire/pull/119/files#diff-135d9107f9ef7ad9140bfab04e9ccb4f331620a0cbed175a047d068e900b1548)

**Comment by groenmarsmannetje** [comment]
And now it broke…. while there was so much time to prevent this from happening. Time to remove this integration because it is clear that it is no longer supported by the developer.

**Comment by KrzysztofHajdamowicz** [comment]
> And now it broke…. while there was so much time to prevent this from happening. Time to remove this integration because it is clear that it is no longer supported by the developer.

I can fork this integration and accept incoming pull requests as a 'respirator'-level maintainer.
