### ISSUE TITLE
Unable to find an entity called weather.xxx

### ISSUE THREAD

**Issue by tjorim** [Limych/ha-snowtire#165]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4978
Installed Version | 2.0.1
Stage | running
Available Repositories | 1463
Downloaded Repositories | 86

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 26, 2025 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-7.ui.nabu.casa
certificate_status | ready
instance_id | 98df8b6855fd40a682abea6ec3befbad
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.10.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 458.4 GB
disk_used | 30.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.13.0), Advanced SSH & Web Terminal (19.0.0), File editor (5.8.0), Zigbee2MQTT (1.40.2-1), Home Assistant Google Drive Backup (0.112.1), The Lounge (0.19.2), Glances (0.21.1), Uptime Kuma (0.12.4), ESPHome (2024.10.1), Mosquitto broker (6.4.1), Firefox (1.3.2), Silicon Labs Flasher (0.3.0), AirCast (4.2.2), eBUSd (23.2.6), Music Assistant Server (2.2.9), Studio Code Server (5.17.2), Get HACS (1.3.1), Tailscale (0.23.1), Zigbee2MQTT Edge (edge)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 43
views | 12
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

api_endpoint_reachable | ok
-- | --
websocket_connection_state | connected
cars_connected | 1
version | v0.19.0

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 12, 2024 at 14:15
-- | --
current_recorder_run | October 22, 2024 at 20:52
estimated_db_size | 1273.62 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-snowtire/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Seems like integration loads faster than weather entity.

### Reproduction steps

1. Update to version 1.6.0
2. Set up new entry
3. Restart home assistant 
4. Check error log

### Debug logs

```text
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:942
First occurred: 20:53:07 (1 occurrences)
Last logged: 20:53:07

Update for binary_sensor.tires_for_ford_c_max fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/snowtire/binary_sensor.py", line 232, in async_update
    await self._async_update()
  File "/config/custom_components/snowtire/binary_sensor.py", line 257, in _async_update
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Unable to find an entity called weather.forecast_home
```

**Comment by fcastilloec** [comment]
This is caused by a raise between loading this integration and the weather one. The only way I know to fix this is to specify the weather integration dependency in the manifest of this extension, but the problem is that we don't all use the same weather integration.
I've tried a lot of things to fix this, but have no idea what to do besides changing the "dependencies" key inside the manifest.json file and put the weather integration you use there.
